# Generated by Django 3.2.13 on 2022-06-25 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_promotion_date', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('planID', models.IntegerField(primary_key=True, serialize=False)),
                ('planName', models.CharField(max_length=100)),
                ('amountOptions', models.CharField(choices=[('13000', '13000'), ('1000', '1000'), ('4000', '4000'), ('5000', '5000'), ('6000', '6000'), ('8000', '8000'), ('3000', '3000'), ('9000', '9000'), ('3500', '3500'), ('2000', '2000'), ('25000', '25500'), ('7500', '7500')], max_length=100)),
                ('startt_promotion_date', models.DateField(editable=False)),
                ('tenureOptions', models.CharField(choices=[('6', '6'), ('12', '12'), ('7', '7'), ('4', '4'), ('3', '3'), ('9', '9'), ('10', '10'), ('5', '5'), ('8', '8'), ('11', '11'), ('2', '2'), ('0', '0'), ('1', '1')], max_length=100)),
                ('benefitPercentage', models.IntegerField(editable=False)),
                ('end_promotion_date', models.DateField(editable=False)),
                ('benefitType', models.CharField(choices=[('extraVoucher', 'extraVoucher'), ('cashback', 'cashback')], max_length=100)),
                ('promoID', models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='promo1', to='TortoiseApp.promotion')),
                ('userID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
